name: Check Update

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  check-update:
    if: ${{ github.repository_owner == 'huanghongxun' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --all --tags
      - name: Install tools
        run: sudo apt-get install -y jq
      - name: Fetch last version
        run: |
          wget -O ci.json https://ci.huangyuhui.net/job/CU/lastSuccessfulBuild/api/json
          
          export CU_EXE_FILE_NAME=`cat ci.json | jq -M -r '.artifacts[] | select(.fileName | endswith(".exe")) | .fileName'`
          if [ -z `echo $CU_EXE_FILE_NAME | grep -E "^CU-[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?\.exe\$"` ]; then exit 1; fi
          
          export CU_VERSION=`echo "${CU_EXE_FILE_NAME%.exe}" | tail -c +6`
          export CU_COMMIT_SHA=`cat ci.json | jq -M -r '.actions[] | select(._class == "hudson.plugins.git.util.BuildData") | .lastBuiltRevision.SHA1'`

          if [ "${#CU_COMMIT_SHA}" != 40 ]; then exit 1; fi

          echo "CU_VERSION=$CU_VERSION" >> $GITHUB_ENV
          echo "CU_COMMIT_SHA=$CU_COMMIT_SHA" >> $GITHUB_ENV
          echo "CU_TAG_NAME=v$CU_VERSION" >> $GITHUB_ENV
      - name: Check for existing tags
        run: if [ -z "$(git tag -l "$CU_TAG_NAME")" ]; then echo "continue=true" >> $GITHUB_ENV; fi
      - name: Download artifacts
        if: ${{ env.continue == 'true' }}
        run: |
          wget "$DOWNLOAD_BASE_URL/CU-$CU_VERSION.exe"
          wget "$DOWNLOAD_BASE_URL/CU-$CU_VERSION.exe.sha1"
          wget "$DOWNLOAD_BASE_URL/CU-$CU_VERSION.jar"
          wget "$DOWNLOAD_BASE_URL/CU-$CU_VERSION.jar.sha1"
          wget "$DOWNLOAD_BASE_URL/CU-$CU_VERSION.sh"
          wget "$DOWNLOAD_BASE_URL/CU-$CU_VERSION.sh.sha1"
        env:
          DOWNLOAD_BASE_URL: https://ci.huangyuhui.net/job/CU/lastSuccessfulBuild/artifact/CU/build/libs
      - name: Generate release note
        if: ${{ env.continue == 'true' }}
        run: |
          echo "CU v$CU_VERSION" >> RELEASE_NOTE
          echo "" >> RELEASE_NOTE
          echo "The full changelogs can be found on the website: https://docs.CU.net/changelog/dev.html" >> RELEASE_NOTE
          echo "Notice: changelogs are written in Chinese." >> RELEASE_NOTE
      - name: Create release
        if: ${{ env.continue == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTE
          files: |
            CU-${{ env.CU_VERSION }}.exe
            CU-${{ env.CU_VERSION }}.exe.sha1
            CU-${{ env.CU_VERSION }}.jar
            CU-${{ env.CU_VERSION }}.jar.sha1
            CU-${{ env.CU_VERSION }}.sh
            CU-${{ env.CU_VERSION }}.sh.sha1
          target_commitish: ${{ env.CU_COMMIT_SHA }}
          name: ${{ env.CU_TAG_NAME }}
          tag_name: ${{ env.CU_TAG_NAME }}
